// <auto-generated />
using System;
using Grosary_net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grosary_net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313050023_AddMeatProducts")]
    partial class AddMeatProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Grosary_net.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Grosary_net.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Grosary_net.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 70,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh boneless chicken breast perfect for grilling and cooking.",
                            ImageUrl = "https://images.pexels.com/photos/616353/pexels-photo-616353.jpeg",
                            Name = "Chicken Breast",
                            Price = 8.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 71,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh goat meat ideal for curries and traditional dishes.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Mutton",
                            Price = 12.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 72,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Premium beef steak perfect for grilling and roasting.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Beef Steak",
                            Price = 14.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 73,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh chicken drumsticks perfect for frying and BBQ.",
                            ImageUrl = "https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg",
                            Name = "Chicken Drumsticks",
                            Price = 7.49m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 74,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh minced meat ideal for burgers and meatballs.",
                            ImageUrl = "https://images.pexels.com/photos/361184/asparagus-steak-veal-chop-361184.jpeg",
                            Name = "Minced Meat",
                            Price = 9.49m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 75,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Lean turkey meat rich in protein and low in fat.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Turkey Meat",
                            Price = 10.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 76,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Tender lamb chops perfect for grilling and roasting.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Lamb Chops",
                            Price = 13.99m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 77,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Juicy sausages perfect for breakfast and grilling.",
                            ImageUrl = "https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg",
                            Name = "Sausages",
                            Price = 6.99m,
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("Grosary_net.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "123",
                            RegistrationDate = new DateTime(2026, 3, 13, 10, 30, 22, 891, DateTimeKind.Local).AddTicks(4467),
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Grosary_net.Models.CartItem", b =>
                {
                    b.HasOne("Grosary_net.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Grosary_net.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
