// <auto-generated />
using System;
using Grosary_net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grosary_net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313050629_AddMoreProducts")]
    partial class AddMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Grosary_net.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Grosary_net.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Grosary_net.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 70,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh boneless chicken breast perfect for grilling and cooking.",
                            ImageUrl = "https://images.pexels.com/photos/616353/pexels-photo-616353.jpeg",
                            Name = "Chicken Breast",
                            Price = 8.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 71,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh goat meat ideal for curries and traditional dishes.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Mutton",
                            Price = 12.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 72,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Premium beef steak perfect for grilling and roasting.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Beef Steak",
                            Price = 14.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 73,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh chicken drumsticks perfect for frying and BBQ.",
                            ImageUrl = "https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg",
                            Name = "Chicken Drumsticks",
                            Price = 7.49m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 74,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Fresh minced meat ideal for burgers and meatballs.",
                            ImageUrl = "https://images.pexels.com/photos/361184/asparagus-steak-veal-chop-361184.jpeg",
                            Name = "Minced Meat",
                            Price = 9.49m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 75,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Lean turkey meat rich in protein and low in fat.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Turkey Meat",
                            Price = 10.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 76,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Tender lamb chops perfect for grilling and roasting.",
                            ImageUrl = "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg",
                            Name = "Lamb Chops",
                            Price = 13.99m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 77,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Meat",
                            Description = "Juicy sausages perfect for breakfast and grilling.",
                            ImageUrl = "https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg",
                            Name = "Sausages",
                            Price = 6.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 101,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Fresh sweet red apples.",
                            ImageUrl = "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
                            Name = "Red Apples",
                            Price = 4.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 102,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Organic bananas rich in potassium.",
                            ImageUrl = "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg",
                            Name = "Bananas",
                            Price = 3.49m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 103,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Sweet fresh strawberries.",
                            ImageUrl = "https://images.pexels.com/photos/89778/strawberries-frisch-ripe-sweet-89778.jpeg",
                            Name = "Strawberries",
                            Price = 6.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 104,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Juicy oranges rich in vitamin C.",
                            ImageUrl = "https://images.pexels.com/photos/327098/pexels-photo-327098.jpeg",
                            Name = "Oranges",
                            Price = 5.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 105,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Sweet tropical mango.",
                            ImageUrl = "https://images.pexels.com/photos/918643/pexels-photo-918643.jpeg",
                            Name = "Mango",
                            Price = 7.49m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 106,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Fresh pineapple.",
                            ImageUrl = "https://images.pexels.com/photos/594589/pexels-photo-594589.jpeg",
                            Name = "Pineapple",
                            Price = 6.49m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 107,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Juicy green grapes.",
                            ImageUrl = "https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg",
                            Name = "Green Grapes",
                            Price = 4.59m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 108,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruits",
                            Description = "Refreshing watermelon.",
                            ImageUrl = "https://images.pexels.com/photos/615705/pexels-photo-615705.jpeg",
                            Name = "Watermelon",
                            Price = 7.49m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 120,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Crunchy salted chips.",
                            ImageUrl = "https://images.pexels.com/photos/568805/pexels-photo-568805.jpeg",
                            Name = "Potato Chips",
                            Price = 2.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 121,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Sweet milk chocolate.",
                            ImageUrl = "https://images.pexels.com/photos/65882/chocolate-dark-coffee-confiserie-65882.jpeg",
                            Name = "Chocolate Bar",
                            Price = 1.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 122,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Crunchy tea biscuits.",
                            ImageUrl = "https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg",
                            Name = "Biscuits",
                            Price = 2.49m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 123,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Salted popcorn snack.",
                            ImageUrl = "https://images.pexels.com/photos/33129/popcorn-movie-party-entertainment.jpg",
                            Name = "Popcorn",
                            Price = 2.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 124,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Crunchy nachos snack.",
                            ImageUrl = "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                            Name = "Nachos",
                            Price = 3.49m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 125,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Sweet cupcake dessert.",
                            ImageUrl = "https://images.pexels.com/photos/357573/pexels-photo-357573.jpeg",
                            Name = "Cupcake",
                            Price = 2.79m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 126,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Fresh baked cookies.",
                            ImageUrl = "https://images.pexels.com/photos/4110541/pexels-photo-4110541.jpeg",
                            Name = "Cookies",
                            Price = 3.49m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 127,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Snacks",
                            Description = "Healthy granola snack.",
                            ImageUrl = "https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg",
                            Name = "Granola Bar",
                            Price = 2.19m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 110,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Fresh green spinach.",
                            ImageUrl = "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
                            Name = "Spinach",
                            Price = 2.49m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 111,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Organic crunchy carrots.",
                            ImageUrl = "https://images.pexels.com/photos/65174/pexels-photo-65174.jpeg",
                            Name = "Carrots",
                            Price = 2.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 112,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Fresh red tomatoes.",
                            ImageUrl = "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg",
                            Name = "Tomatoes",
                            Price = 3.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 113,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Fresh green bell peppers.",
                            ImageUrl = "https://images.pexels.com/photos/128420/pexels-photo-128420.jpeg",
                            Name = "Bell Peppers",
                            Price = 2.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 114,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Healthy broccoli.",
                            ImageUrl = "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
                            Name = "Broccoli",
                            Price = 3.49m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 115,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Fresh cucumber.",
                            ImageUrl = "https://images.pexels.com/photos/2329440/pexels-photo-2329440.jpeg",
                            Name = "Cucumber",
                            Price = 2.29m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 116,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Fresh red onions.",
                            ImageUrl = "https://images.pexels.com/photos/175414/pexels-photo-175414.jpeg",
                            Name = "Onions",
                            Price = 2.39m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 117,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Vegetables",
                            Description = "Farm fresh potatoes.",
                            ImageUrl = "https://images.pexels.com/photos/144248/potatoes-food-vegetables-organic-144248.jpeg",
                            Name = "Potatoes",
                            Price = 3.19m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 130,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Fresh orange juice.",
                            ImageUrl = "https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg",
                            Name = "Orange Juice",
                            Price = 3.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 131,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Natural apple juice.",
                            ImageUrl = "https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg",
                            Name = "Apple Juice",
                            Price = 3.49m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 132,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Cold cola beverage.",
                            ImageUrl = "https://images.pexels.com/photos/2983101/pexels-photo-2983101.jpeg",
                            Name = "Cola Drink",
                            Price = 2.49m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 133,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Refreshing energy drink.",
                            ImageUrl = "https://images.pexels.com/photos/2775860/pexels-photo-2775860.jpeg",
                            Name = "Energy Drink",
                            Price = 3.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 134,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Iced coffee drink.",
                            ImageUrl = "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
                            Name = "Cold Coffee",
                            Price = 4.49m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 135,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Healthy green tea.",
                            ImageUrl = "https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg",
                            Name = "Green Tea",
                            Price = 3.19m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 136,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Sweet milkshake drink.",
                            ImageUrl = "https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg",
                            Name = "Milkshake",
                            Price = 4.29m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 137,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Beverages",
                            Description = "Pure drinking water.",
                            ImageUrl = "https://images.pexels.com/photos/327090/pexels-photo-327090.jpeg",
                            Name = "Mineral Water",
                            Price = 1.49m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 140,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Fresh salmon fish.",
                            ImageUrl = "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg",
                            Name = "Salmon Fish",
                            Price = 12.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 141,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Premium tuna fish.",
                            ImageUrl = "https://images.pexels.com/photos/3296277/pexels-photo-3296277.jpeg",
                            Name = "Tuna Fish",
                            Price = 11.49m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 142,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Fresh shrimp seafood.",
                            ImageUrl = "https://images.pexels.com/photos/566345/pexels-photo-566345.jpeg",
                            Name = "Shrimp",
                            Price = 13.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 143,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Fresh sea crab.",
                            ImageUrl = "https://images.pexels.com/photos/3296390/pexels-photo-3296390.jpeg",
                            Name = "Crab",
                            Price = 14.49m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 144,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Premium lobster seafood.",
                            ImageUrl = "https://images.pexels.com/photos/566345/pexels-photo-566345.jpeg",
                            Name = "Lobster",
                            Price = 19.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 145,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Fresh sardine fish.",
                            ImageUrl = "https://images.pexels.com/photos/3296390/pexels-photo-3296390.jpeg",
                            Name = "Sardines",
                            Price = 8.49m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 146,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Fresh tilapia fish.",
                            ImageUrl = "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg",
                            Name = "Tilapia",
                            Price = 9.99m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 147,
                            AddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Seafood",
                            Description = "Fresh prawns seafood.",
                            ImageUrl = "https://images.pexels.com/photos/566345/pexels-photo-566345.jpeg",
                            Name = "Prawns",
                            Price = 12.49m,
                            StockQuantity = 28
                        });
                });

            modelBuilder.Entity("Grosary_net.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "123",
                            RegistrationDate = new DateTime(2026, 3, 13, 10, 36, 28, 947, DateTimeKind.Local).AddTicks(7466),
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Grosary_net.Models.CartItem", b =>
                {
                    b.HasOne("Grosary_net.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Grosary_net.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
